apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mywebfuncs-kn
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "10"
    spec:
      containers:
      - image: quay.io/miheinr/mywebfuncs
