apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-manifests
spec:
  workspaces:
  - name: source
  params:
    - name: manifest_dir
      description: The directory in source that contains yaml manifests
      type: string
      default: "k8s"
  steps:
    - name: create
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source
      command: ["/bin/bash", "-c"]
      args:
        - |-
          echo Creating manifests in $(inputs.params.manifest_dir) directory
          oc create -f $(inputs.params.manifest_dir) 2>/dev/null || echo "Warning: Some objects already exist"
          echo -----------------------------------
